### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'model'

### ISSUE THREAD

**Issue by JD-2006** [ljzycmd/SimDeblur#15]
Here is my argument: python inference_image.py configs/base_dvd.yaml demo/dbn_ckpt.pth --img=2016-3A-00000.png --save_path=inference_results

Traceback (most recent call last):
  File "C:\Users\Test\Documents\Image_Scripts\SimDeblur\inference_image.py", line 81, in <module>
    inference()
  File "C:\Users\Test\Documents\Image_Scripts\SimDeblur\inference_image.py", line 46, in inference
    arch = build_meta_arch(cfg)
  File "C:\Users\Test\Documents\Image_Scripts\SimDeblur\simdeblur\model\build.py", line 38, in build_meta_arch
    ret = META_ARCH_REGISTRY.get(name)(cfg)
  File "C:\Users\Test\Documents\Image_Scripts\SimDeblur\simdeblur\model\meta_arch\plain_cnn.py", line 40, in __init__
    self.model = self.build_model(cfg).to(self.device)
  File "C:\Users\Test\Documents\Image_Scripts\SimDeblur\simdeblur\model\meta_arch\base_arch.py", line 76, in build_model
    model = build_backbone(cfg.model)
AttributeError: 'EasyDict' object has no attribute 'model'

**Comment by ljzycmd** [comment]
Hi @JD-2006, with the above details, you may use the **wrong** config file during inference. Note that `configs/base_dvd.yaml` is a config for `DVD` video deblurring dataset, not including the model config.

You should use a config file that contains a specified model configuration for single image deblurring, e.g., config yaml in folder `configs/srn, configs/minmounet`.

**Comment by JD-2006** [comment]
Thanks that fixed it!

p.s. Any chance of a Restormer yaml?

**Comment by ljzycmd** [comment]
Hi @JD-2006, I have updated the configs for the Restormer model. Please check.
